### ISSUE TITLE
harmonization error

### ISSUE THREAD

**Issue by raven38** [tohinz/ConSinGAN#2]
Hi, I'm trying to run your implementation.

I run a command in your README.
```
python main_train.py --gpu 0 --train_mode harmonization --train_stages 3 --min_size 120 --lrelu_alpha 0.3 --niter 1000 --batch_norm --input_name Images/Harmonization/scream.jpg
```

I faced a error.
```
Traceback (most recent call last):
  File "main_train.py", line 111, in <module>
    train(opt)
  File "/home/ConSinGAN/training_harmonization_editing.py", line 75, in train
    naive_img, naive_img_large, fixed_noise,
UnboundLocalError: local variable 'naive_img_large' referenced before assignment
```

Help me.

**Comment by tohinz** [comment]
Thanks, the error should be fixed now and the command should run without problems.
